FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24 AS builder

COPY cert-manager-operator/bundle/manifests /manifests
COPY cert-manager-operator/bundle/metadata /metadata
COPY cert-manager-operator/bundle/tests/scorecard /tests/scorecard
COPY cert-manager-operator/LICENSE /licenses/
COPY --chmod=0550 hack/bundle/render_templates.sh /render_templates.sh

# Below image versions are used for replacing the image references in the operator CSV.
# For image builds through konflux, konflux-bot will update the references.
ARG CERT_MANAGER_OPERATOR_IMAGE=registry.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:766d583f7fd2dcffa968cae98974d8d8f39f9eb74929c95dedab92cb91752962 \
    CERT_MANAGER_WEBHOOK_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:3025551497a7a58b7baf4246f48b8350d59bfa186fd24b7e2049700f30fdad73 \
    CERT_MANAGER_CA_INJECTOR_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:3025551497a7a58b7baf4246f48b8350d59bfa186fd24b7e2049700f30fdad73 \
    CERT_MANAGER_CONTROLLER_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:3025551497a7a58b7baf4246f48b8350d59bfa186fd24b7e2049700f30fdad73 \
    CERT_MANAGER_ACMESOLVER_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:1ba7349edafaba5adc573e58e82ee45f73e3827889f8dc9ce54137679d79f381 \
    CERT_MANAGER_ISTIOCSR_IMAGE=registry.redhat.io/cert-manager/cert-manager-istio-csr-rhel9@sha256:9ea2c29a384b964cef14f853278821df3cd30320f25afab8823897192f67fc7e

ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1
ENV GOFLAGS=""

COPY tools.go go.mod go.sum /
RUN go build -o /usr/bin/yq github.com/mikefarah/yq/v4 && chmod +x /usr/bin/yq
RUN ./render_templates.sh /manifests /metadata \
    "${CERT_MANAGER_OPERATOR_IMAGE}" \
    "${CERT_MANAGER_WEBHOOK_IMAGE}" \
    "${CERT_MANAGER_CA_INJECTOR_IMAGE}" \
    "${CERT_MANAGER_CONTROLLER_IMAGE}" \
    "${CERT_MANAGER_ACMESOLVER_IMAGE}" \
    "${CERT_MANAGER_ISTIOCSR_IMAGE}"

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL

# Core bundle labels.
LABEL com.redhat.component="cert-manager-operator-bundle-container" \
      name="cert-manager/cert-manager-operator-bundle" \
      summary="Cert Manager support for OpenShift" \
      description="Cert Manager support for OpenShift" \
      distribution-scope="public" \
      release="${RELEASE_VERSION}" \
      version="${RELEASE_VERSION}" \
      url="${SOURCE_URL}" \
      maintainer="Red Hat, Inc." \
      vendor="Red Hat, Inc." \
      com.redhat.delivery.operator.bundle=true \
      com.redhat.openshift.versions="v4.16-v4.20" \
      io.openshift.expose-services="" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.openshift.maintainer.product="OpenShift Container Platform" \
      io.openshift.tags="openshift,cert,cert-manager,cert-manager-operator,tls" \
      io.k8s.display-name="openshift-cert-manager-operator-bundle" \
      io.k8s.description="cert-manager-operator-bundle-container" \
      operators.operatorframework.io.bundle.mediatype.v1="registry+v1" \
      operators.operatorframework.io.bundle.manifests.v1=manifests/ \
      operators.operatorframework.io.bundle.metadata.v1=metadata/ \
      operators.operatorframework.io.bundle.package.v1="openshift-cert-manager-operator" \
      operators.operatorframework.io.bundle.channel.default.v1="stable-v1" \
      operators.operatorframework.io.bundle.channels.v1="stable-v1,stable-v1.17" \
      operators.operatorframework.io.metrics.builder="operator-sdk-v1.25.1" \
      operators.operatorframework.io.metrics.mediatype.v1="metrics+v1" \
      operators.operatorframework.io.metrics.project_layout="go.kubebuilder.io/v3" \
      cpe="cpe:/a:redhat:cert_manager:1.17::el9"

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1 \
      operators.operatorframework.io.test.config.v1=tests/scorecard/

COPY --from=builder /manifests /manifests
COPY --from=builder /metadata /metadata
COPY --from=builder /tests/scorecard /tests/scorecard
COPY --from=builder /licenses /licenses

USER 65534:65534
