FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24 AS builder

COPY cert-manager-operator/bundle/manifests /manifests
COPY cert-manager-operator/bundle/metadata /metadata
COPY cert-manager-operator/bundle/tests/scorecard /tests/scorecard
COPY cert-manager-operator/LICENSE /licenses/
COPY --chmod=0550 hack/bundle/render_templates.sh /render_templates.sh

# Below image versions are used for replacing the image references in the operator CSV.
# For image builds through konflux, konflux-bot will update the references.
ARG CERT_MANAGER_OPERATOR_IMAGE=registry.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:99526f5a179816df1f7f51df0517136b247d815b7bdce0a5d0eb7cdaf4b5ce7a \
    CERT_MANAGER_WEBHOOK_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:903ce74138b1ffc735846a7c5fcdf62bbe82ca29568a6b38caec2656f6637671 \
    CERT_MANAGER_CA_INJECTOR_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:903ce74138b1ffc735846a7c5fcdf62bbe82ca29568a6b38caec2656f6637671 \
    CERT_MANAGER_CONTROLLER_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:903ce74138b1ffc735846a7c5fcdf62bbe82ca29568a6b38caec2656f6637671 \
    CERT_MANAGER_ACMESOLVER_IMAGE=registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:38899dcd99bcd1c8c8d2c67cd19d5b1756434028ed2f1b926a282723bd63183e \
    CERT_MANAGER_ISTIOCSR_IMAGE=registry.redhat.io/cert-manager/cert-manager-istio-csr-rhel9@sha256:fb89adfcc4bcdaf21bed27dbc90586fb2b32180259b9f9d6fcf84a38e401fe03

ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1
ENV GOFLAGS=""

COPY tools.go go.mod go.sum /
RUN go build -o /usr/bin/yq github.com/mikefarah/yq/v4 && chmod +x /usr/bin/yq
RUN ./render_templates.sh /manifests /metadata \
    "${CERT_MANAGER_OPERATOR_IMAGE}" \
    "${CERT_MANAGER_WEBHOOK_IMAGE}" \
    "${CERT_MANAGER_CA_INJECTOR_IMAGE}" \
    "${CERT_MANAGER_CONTROLLER_IMAGE}" \
    "${CERT_MANAGER_ACMESOLVER_IMAGE}" \
    "${CERT_MANAGER_ISTIOCSR_IMAGE}"

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL

# Core bundle labels.
LABEL com.redhat.component="cert-manager-operator-bundle-container" \
      cpe="cpe:/a:redhat:cert_manager:1.18::el9" \
      name="cert-manager/cert-manager-operator-bundle" \
      summary="Cert Manager support for OpenShift" \
      description="Cert Manager support for OpenShift" \
      distribution-scope="public" \
      release="${RELEASE_VERSION}" \
      version="${RELEASE_VERSION}" \
      url="${SOURCE_URL}" \
      maintainer="Red Hat, Inc." \
      vendor="Red Hat, Inc." \
      com.redhat.delivery.operator.bundle=true \
      com.redhat.openshift.versions="v4.17-v4.21" \
      io.openshift.expose-services="" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.openshift.maintainer.product="OpenShift Container Platform" \
      io.openshift.tags="openshift,cert,cert-manager,cert-manager-operator,tls" \
      io.k8s.display-name="openshift-cert-manager-operator-bundle" \
      io.k8s.description="cert-manager-operator-bundle-container" \
      operators.operatorframework.io.bundle.mediatype.v1="registry+v1" \
      operators.operatorframework.io.bundle.manifests.v1=manifests/ \
      operators.operatorframework.io.bundle.metadata.v1=metadata/ \
      operators.operatorframework.io.bundle.package.v1="openshift-cert-manager-operator" \
      operators.operatorframework.io.bundle.channel.default.v1="stable-v1" \
      operators.operatorframework.io.bundle.channels.v1="stable-v1,stable-v1.18" \
      operators.operatorframework.io.metrics.builder="operator-sdk-v1.25.1" \
      operators.operatorframework.io.metrics.mediatype.v1="metrics+v1" \
      operators.operatorframework.io.metrics.project_layout="go.kubebuilder.io/v3"

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1 \
      operators.operatorframework.io.test.config.v1=tests/scorecard/

COPY --from=builder /manifests /manifests
COPY --from=builder /metadata /metadata
COPY --from=builder /tests/scorecard /tests/scorecard
COPY --from=builder /licenses /licenses

USER 65534:65534
