FROM registry.access.redhat.com/ubi9/go-toolset:1.26.7-1791182877 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/cert-manager-operator"
ARG COMMIT_SHA
WORKDIR $SOURCE_DIR
# rhel9/go-toolset runs as a non-root user by default; switch to root in this
# builder stage so we can build binaries in place.
USER 0

COPY cert-manager-operator $SOURCE_DIR
COPY cert-manager-operator/LICENSE /licenses/

ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1
ENV GOFLAGS=""
ENV GOBUILD_BUILD_FLAGS='-w -s -X github.com/openshift/cert-manager-operator/pkg/version.COMMIT=${COMMIT_SHA}'

RUN go build -o "$SOURCE_DIR/cert-manager-operator" -ldflags "${GOBUILD_BUILD_FLAGS}" -tags "${GO_BUILD_TAGS}" main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae

# Values for below ARGs will passed from tekton configs for konflux builds.
## Release version of the cert-manager-operator source code used in the build.
ARG RELEASE_VERSION
## Commit hash that considered for the image build.
ARG COMMIT_SHA
## github URL of the cert-manager-operator source repository.
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/cert-manager-operator"

COPY --from=builder $SOURCE_DIR/cert-manager-operator /usr/bin/
COPY --from=builder /licenses /licenses

USER 65534:65534

LABEL com.redhat.component="cert-manager-operator-container" \
      cpe="cpe:/a:redhat:cert_manager:1.20::el9" \
      name="cert-manager/cert-manager-operator-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="cert-manager-operator" \
      maintainer="Red Hat, Inc." \
      description="cert-manager-operator-container" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.expose-services="" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.openshift.maintainer.product="OpenShift Container Platform" \
      io.openshift.tags="data,images,operator,cert-manager" \
      io.k8s.display-name="openshift-cert-manager-operator" \
      io.k8s.description="cert-manager-operator-container"

ENTRYPOINT ["/usr/bin/cert-manager-operator"]
