FROM registry.access.redhat.com/ubi9/go-toolset:9.8-1791275853 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/cert-manager-trust-manager"
WORKDIR $SOURCE_DIR
# rhel9/go-toolset runs as a non-root user by default; switch to root in this
# builder stage so we can build binaries in place.
USER 0

COPY trust-manager $SOURCE_DIR
COPY trust-manager/LICENSE /licenses/

ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1
ENV GOFLAGS=""

RUN cd $SOURCE_DIR/cmd/trust-manager && go build -o $SOURCE_DIR/_output/cert-manager-trust-manager -ldflags '-w -s' -tags ${GO_BUILD_TAGS} main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:beeada7dd17903dfb69fd5f6916c054720bf28a52daaa2f7a1910a1394244bd2

# Values for below ARGs will passed from tekton configs for konflux builds.
## Release version of the cert-manager source code used in the build.
ARG RELEASE_VERSION
## Commit hash that considered for the image build.
ARG COMMIT_SHA
## github URL of the cert-manager source repository.
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/cert-manager-trust-manager"

COPY --from=builder $SOURCE_DIR/_output/cert-manager-trust-manager /usr/local/bin/cert-manager-trust-manager
COPY --from=builder /licenses /licenses

USER 65534:65534

LABEL com.redhat.component="cert-manager-trust-manager-container" \
      cpe="cpe:/a:redhat:cert_manager:1.20::el9" \
      name="cert-manager/cert-manager-trust-manager-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="cert-manager-trust-manager" \
      maintainer="Red Hat, Inc." \
      description="cert-manager-trust-manager-container" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images,cert-manager-trust-manager" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.k8s.display-name="cert-manager-trust-manager" \
      io.k8s.description="cert-manager-trust-manager-container"

ENTRYPOINT ["/usr/local/bin/cert-manager-trust-manager"]
